### ISSUE TITLE
Re-order iconbar icons

### ISSUE THREAD

**Issue by thenoobtester** [luebking/fluxbox#1]
Hi,

could it be possible to add the possibility to re-order icons on the iconbar? Now they are fixed by the opening order but I like to re-order the window icons after opening and closing many, just like you can with tabs in a browser.

I don't know C++ but if you can point me to where this could be handled I could try to have a look at it?

This feature has been requested for 17 years now and has never been implemented.

Thank you

**Comment by luebking** [comment]
This is just a fork of a gone repo (maybe I should deactivate it)
=> https://github.com/fluxbox/fluxbox

If you however mean to drag around the icon, that's probably not too hard to do in src/Icon{Button,barTool}*

**Comment by thenoobtester** [comment]
Thank you for the answer :) I will try then.
